/*
Each new term in the Fibonacci sequence is generated by 
adding the previous two terms. By starting with 1 and 2, 
the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci 
sequence whose values do not exceed 
four million, find the sum of the even-valued terms.
*/
#include "stdio.h"

int main(){
	int temp1, temp2, latestNumber = 0, sum = 2; 
	temp1 = 1;
	temp2 = 2; 

	while (latestNumber < 4000000) {
		if(latestNumber % 2 == 0) sum += latestNumber;
		printf("%i, ", latestNumber);

		latestNumber = temp1 + temp2;
		temp1 = temp2;
		temp2 = latestNumber;
	}
	printf("\n%i", sum);
	return 0;
}